### ISSUE TITLE
chess board photos

### ISSUE THREAD

**Issue by geminikop** [TemugeB/python_stereo_camera_calibrate#2]
Hi Temuge,
Thank you for your nice work and sharing. I read your post about camera calibration in detail and found your link to calibration frames didn't work. Could you please post them again so I can download? That will be very helpful. I will appreciate your any response.

Thanks,
Rui

**Comment by TemugeB** [comment]
Hey thanks for letting me know. I was cleaning out my google drive and accidentally deleted the frames. So those frames are gone. Could you try with these: [link](https://drive.google.com/file/d/1o6OVbxi6dT0kDinmUQaBrEZBF3vz_kDp/view?usp=sharing)? Let me know if this works, I will update the blog post with these frames if they do.

**Comment by geminikop** [comment]
> Hey thanks for letting me know. I was cleaning out my google drive and accidentally deleted the frames. So those frames are gone. Could you try with these: [link](https://drive.google.com/file/d/1o6OVbxi6dT0kDinmUQaBrEZBF3vz_kDp/view?usp=sharing)? Let me know if this works, I will update the blog post with these frames if they do.

The link works. I appreciate that. Thanks again.

**Comment by TemugeB** [comment]
No I mean did the calibration code work fine with the new frames?

**Comment by geminikop** [comment]
> No I mean did the calibration code work fine with the new frames?
Yes it works fine

**Comment by geminikop** [comment]
But the rmse return by stereo_calibrate func is >0.5. Is that good?

**Comment by TemugeB** [comment]
How much was it? I got 0.502, which is ok.

**Comment by geminikop** [comment]
> 

I got the same. So what range is good usually?

**Comment by TemugeB** [comment]
Ideally you would want less than 0.5. I don't think I managed less than 0.3. Due to camera resolution and pixel to floating point conversions, there will always be some error, even if the calibration pattern is correctly obtained. In any case, 0.5 is acceptable and you can try different frames until you go below it. Technically what it is measuring is the error of re projection in pixel space. So an average per pixel error of 0.5 is not bad at all. In other words you have about 50% probability that the correct pixel is shifted by one pixel.

**Comment by geminikop** [comment]
I get it! Thanks.
